// 16 Dog Personality Types - Brandable, Shareable, Viral-friendly
// Designed for Korean consumer startup aesthetics

export interface PersonalityTypeData {
  id: string
  name: string
  subtitle: string
  tags: string[]
  emoji: string
  color: string
  mbti: string
  summary: string
  description: string
  behaviors: string[]
  aloneReaction: string
  recommendedRoutine: string[]
  playStyle: string[]
  strengths: string[]
  careAdvice: string[]
  compatibility: { type: string; score: number }[]
  hashtag: string
}

export const personalityTypes: PersonalityTypeData[] = [
  {
    id: "sofa-watcher",
    name: "소파감시자",
    subtitle: "소파 위에서 세상을 주시함",
    tags: ["#감시자", "#관찰자", "#소파왕"],
    emoji: "👀",
    color: "from-slate-400 to-zinc-500",
    mbti: "ISTJ",
    summary: "소파 위에서 모든 것을 체크하는 관찰자",
    description: "소파가 내 왕좌예요. 거기서 온 집안을 감시하죠. 보호자가 어디 가는지, 뭘 하는지 다 체크하면서도 티 안 내는 게 프로. 눈만 굴려도 다 파악하는 센서급 관찰력.",
    behaviors: ["소파에서 모든 걸 감시", "눈으로 보호자 추적", "자리 지키면서 상황 파악", "움직임 최소화로 에너지 절약"],
    aloneReaction: "소파에서 기다리다 현관 체크",
    recommendedRoutine: ["정해진 시간에 밥주기", "소파 타임 보장", "규칙적인 산책 루틴"],
    playStyle: ["앉아서 하는 간식 놀이", "노즈워크", "관찰하며 터그놀이"],
    strengths: ["관찰력 만렙", "차분한 성격", "에너지 효율 최고"],
    careAdvice: ["루틴 유지가 핵심", "천천히 신뢰 쌓기", "자리 존중해주기"],
    compatibility: [{ type: "집순이/집돌이 보호자", score: 95 }, { type: "규칙적인 생활러", score: 88 }],
    hashtag: "#소파감시자"
  },
  {
    id: "clingy-lover",
    name: "껌딱지러버",
    subtitle: "24시간 붙어있고 싶어요",
    tags: ["#껌딱지", "#밀착형", "#애교폭탄"],
    emoji: "🥺",
    color: "from-pink-400 to-rose-400",
    mbti: "ISFJ",
    summary: "보호자 곁이 제일 안전한 세상",
    description: "껌딱지? 저 맞아요. 화장실까지 따라가고, 1초도 떨어지기 싫어요. 무릎 위가 천국, 품에 안기면 세상 다 가진 기분. 분리불안은 사랑이 넘쳐서예요!",
    behaviors: ["화장실까지 따라감", "품에 안기려고 점프", "눈 마주치면 꼬리 폭풍", "1초도 떨어지기 싫어"],
    aloneReaction: "문 앞에서 울면서 기다림",
    recommendedRoutine: ["분리 연습 조금씩", "스킨십 타임 보장", "외출 전 차분한 루틴"],
    playStyle: ["보호자랑 같이 하는 모든 것", "안고 간식 주기", "밀착 터그놀이"],
    strengths: ["애정 무한대", "애교 만렙", "스킨십 천재"],
    careAdvice: ["분리불안 관리 필수", "독립심 훈련 천천히", "안정감 있는 환경"],
    compatibility: [{ type: "재택근무러", score: 98 }, { type: "스킨십 좋아하는 보호자", score: 95 }],
    hashtag: "#껌딱지러버"
  },
  {
    id: "sensitive-sensor",
    name: "예민센서",
    subtitle: "모든 소리가 다 들려요",
    tags: ["#예민보스", "#소리감지", "#초감각"],
    emoji: "🦋",
    color: "from-violet-400 to-purple-400",
    mbti: "INFP",
    summary: "세상의 모든 소리를 감지하는 초감각",
    description: "천둥소리? 공포! 초인종? 경보발령! 작은 소리도 놓치지 않는 초고감도 센서예요. 예민하지만 그만큼 보호자 감정도 잘 읽어서 힘들 때 곁에 와줘요.",
    behaviors: ["작은 소리에 귀 쫑긋", "낯선 상황에 숨음", "보호자 기분 100% 감지", "안전한 곳 찾아다님"],
    aloneReaction: "불안해하며 숨어서 기다림",
    recommendedRoutine: ["조용한 환경 유지", "천천히 사회화", "칭찬 많이 해주기"],
    playStyle: ["조용한 노즈워크", "숨바꼭질", "진정 음악과 함께"],
    strengths: ["감정 교감 능력", "충성심 최고", "눈치 빠름"],
    careAdvice: ["스트레스 환경 최소화", "점진적 적응 훈련", "많은 칭찬과 격려"],
    compatibility: [{ type: "차분한 보호자", score: 95 }, { type: "조용한 가정환경", score: 92 }],
    hashtag: "#예민센서"
  },
  {
    id: "solo-explorer",
    name: "혼놀탐험가",
    subtitle: "혼자 놀아도 재밌어요",
    tags: ["#혼놀러", "#독립심", "#탐험가"],
    emoji: "🔍",
    color: "from-amber-400 to-orange-400",
    mbti: "ENFP",
    summary: "혼자서도 신나게 탐험하는 독립왕",
    description: "혼자 있어도 심심하지 않아요! 집 구석구석 탐험하고, 장난감 찾아다니고, 냄새 맡으며 하루가 금방 가요. 보호자 없어도 알아서 척척!",
    behaviors: ["혼자 집 탐험", "장난감 스스로 찾아 놂", "숨겨둔 간식 발굴", "독립적으로 산책 탐색"],
    aloneReaction: "집 탐험하다 보호자 맞이",
    recommendedRoutine: ["새로운 장난감 제공", "노즈워크 훈련", "탐험할 공간 확보"],
    playStyle: ["노즈워크 매트", "퍼즐 피더", "보물찾기"],
    strengths: ["독립심 강함", "적응력 높음", "지루할 틈 없음"],
    careAdvice: ["탐험 환경 안전하게", "두뇌 자극 놀이", "혼자 시간도 OK"],
    compatibility: [{ type: "바쁜 직장인", score: 96 }, { type: "독립적인 보호자", score: 91 }],
    hashtag: "#혼놀탐험가"
  },
  {
    id: "routine-master",
    name: "루틴마스터",
    subtitle: "매일 똑같이가 최고예요",
    tags: ["#루틴러", "#규칙적", "#예측가능"],
    emoji: "⏰",
    color: "from-yellow-400 to-amber-400",
    mbti: "ESFJ",
    summary: "정해진 루틴대로 살아가는 규칙왕",
    description: "밥 시간, 산책 시간, 잠자리 시간... 모든 게 정해져 있어야 편해요. 루틴이 깨지면 불안! 매일 똑같은 게 최고의 행복이에요.",
    behaviors: ["밥 시간에 밥그릇 앞 대기", "산책 시간에 현관 앞 대기", "잠잘 시간에 자리 찾아감", "변화에 적응 느림"],
    aloneReaction: "정해진 자리에서 기다림",
    recommendedRoutine: ["철저한 시간표 유지", "매일 같은 산책 코스", "예측 가능한 일과"],
    playStyle: ["정해진 시간 놀이", "반복적인 훈련", "익숙한 장난감"],
    strengths: ["예측 가능한 행동", "안정적인 성격", "훈련 습득 빠름"],
    careAdvice: ["루틴 변화 최소화", "예고하고 변경하기", "일관성 유지"],
    compatibility: [{ type: "규칙적인 생활러", score: 98 }, { type: "체계적인 보호자", score: 90 }],
    hashtag: "#루틴마스터"
  },
  {
    id: "wait-master",
    name: "기다림장인",
    subtitle: "기다리는 건 자신 있어요",
    tags: ["#기다림장인", "#인내심", "#충성러"],
    emoji: "⏳",
    color: "from-orange-500 to-rose-500",
    mbti: "ENFJ",
    summary: "보호자를 묵묵히 기다리는 충성왕",
    description: "보호자가 돌아올 때까지 같은 자리에서 기다려요. 현관문 앞이 내 자리! 기다림이 힘들어도 돌아올 걸 알기에 참을 수 있어요. 돌아오면 세상 행복!",
    behaviors: ["현관 앞 대기가 일상", "밖에서 발소리만 들어도 꼬리 흔들기", "같은 자리에서 기다리기", "돌아오면 미친듯이 반김"],
    aloneReaction: "현관 앞에서 묵묵히 기다림",
    recommendedRoutine: ["외출 전 안심 루틴", "돌아와서 충분한 인사", "기다림 보상 간식"],
    playStyle: ["돌아온 후 함께 놀기", "터그놀이", "공놀이"],
    strengths: ["인내심 최고", "충성심", "기다림의 美"],
    careAdvice: ["너무 오래 혼자 두지 않기", "돌아오면 충분히 인사", "기다림 보상해주기"],
    compatibility: [{ type: "출퇴근하는 직장인", score: 95 }, { type: "예측 가능한 생활러", score: 92 }],
    hashtag: "#기다림장인"
  },
  {
    id: "door-radar",
    name: "현관레이더",
    subtitle: "현관문 소리가 다 들려요",
    tags: ["#현관지킴이", "#청각레이더", "#경비견"],
    emoji: "📡",
    color: "from-green-500 to-emerald-500",
    mbti: "ESTP",
    summary: "현관의 모든 소리를 감지하는 레이더",
    description: "초인종? 택배? 발소리? 현관에서 나는 모든 소리를 완벽 감지! 보호자가 오는 소리는 3층 아래에서도 알아채요. 현관을 지키는 게 내 사명!",
    behaviors: ["현관 소리에 바로 반응", "엘리베이터 소리 구분", "택배 오면 알림 짖음", "보호자 발소리 3층 앞에서 감지"],
    aloneReaction: "현관 앞에서 귀 쫑긋 대기",
    recommendedRoutine: ["현관 훈련하기", "소리 반응 조절 연습", "적절한 경계 칭찬"],
    playStyle: ["현관 앞 대기 놀이", "소리 찾기 게임", "경비견 놀이"],
    strengths: ["청각 만렙", "경계심", "충성심"],
    careAdvice: ["과도한 짖음 관리", "적절한 경계 허용", "소리 둔감화 훈련"],
    compatibility: [{ type: "경비견 원하는 보호자", score: 96 }, { type: "짖음 OK인 환경", score: 91 }],
    hashtag: "#현관레이더"
  },
  {
    id: "treat-hunter",
    name: "간식헌터",
    subtitle: "간식이면 뭐든 해요",
    tags: ["#간식러버", "#식탐왕", "#헌터본능"],
    emoji: "🦴",
    color: "from-amber-500 to-yellow-500",
    mbti: "ENTP",
    summary: "간식을 위해서라면 뭐든지 하는 식탐왕",
    description: "간식 봉지 바스락 소리만 들어도 달려와요! 훈련? 간식 있으면 천재급으로 습득. 간식 앞에선 모든 게 가능한 식탐의 화신!",
    behaviors: ["간식 봉지 소리에 텔레포트", "간식 위치 완벽 파악", "간식 있으면 뭐든 함", "숨긴 간식 100% 발굴"],
    aloneReaction: "간식 찾아 탐색하다 기다림",
    recommendedRoutine: ["간식 활용 훈련", "노즈워크로 간식 찾기", "식탐 조절 연습"],
    playStyle: ["간식 숨기기 게임", "노즈워크 매트", "퍼즐 피더"],
    strengths: ["훈련 쉬움(간식으로)", "적극적", "에너지 넘침"],
    careAdvice: ["과식 주의", "건강한 간식 선택", "식탐 이용한 훈련"],
    compatibility: [{ type: "훈련 열정 있는 보호자", score: 98 }, { type: "간식으로 동기부여", score: 95 }],
    hashtag: "#간식헌터"
  },
  {
    id: "walk-engine",
    name: "산책엔진",
    subtitle: "산책이 삶의 이유예요",
    tags: ["#산책러", "#야외파", "#달리기왕"],
    emoji: "🏃",
    color: "from-red-500 to-orange-500",
    mbti: "ENTJ",
    summary: "산책이 인생의 전부인 아웃도어 러버",
    description: "리드줄만 봐도 미친듯이 흥분! 산책 시간이 하루의 하이라이트고, 안 가면 온 집안을 난장판으로 만들어요. 밖에서 뛰는 게 제일 행복!",
    behaviors: ["리드줄 보면 점프", "산책 전 흥분 폭발", "밖에선 달리기 모드", "산책 끝나면 아쉬워함"],
    aloneReaction: "다음 산책만 기다리며 대기",
    recommendedRoutine: ["하루 2회 이상 산책 필수", "달리기 시간 확보", "다양한 코스 개발"],
    playStyle: ["야외 달리기", "공 던지기", "프리스비"],
    strengths: ["체력 무한대", "활발함", "건강함"],
    careAdvice: ["충분한 운동 필수", "비 오는 날 대체 활동", "산책 못하면 실내 놀이"],
    compatibility: [{ type: "운동 좋아하는 보호자", score: 99 }, { type: "야외활동 가능", score: 96 }],
    hashtag: "#산책엔진"
  },
  {
    id: "attention-collector",
    name: "관심수집가",
    subtitle: "관심이 없으면 못 살아요",
    tags: ["#관심종자", "#애교부자", "#관종"],
    emoji: "🌟",
    color: "from-fuchsia-500 to-pink-500",
    mbti: "ESFP",
    summary: "모든 사람의 관심을 수집하는 애교왕",
    description: "나 좀 봐줘요! 관심이 필요해요! 모든 사람의 시선을 끌고 싶어하는 진정한 관종. 애교로 모든 걸 해결하고, 관심 안 주면 삐져요.",
    behaviors: ["손님 오면 애교 폭발", "관심 안 주면 삐침", "모든 사람에게 친근", "사진 찍히는 거 좋아함"],
    aloneReaction: "심심해서 소리 내거나 난리",
    recommendedRoutine: ["충분한 관심 시간", "사회화 활동", "혼자 있는 연습도"],
    playStyle: ["모든 사람과 놀기", "애교 배틀", "사진 찍기"],
    strengths: ["사교성 최고", "애교 만렙", "밝은 성격"],
    careAdvice: ["충분한 관심", "혼자 있는 훈련", "과도한 관심 요구 조절"],
    compatibility: [{ type: "관심 많이 주는 보호자", score: 98 }, { type: "대가족", score: 94 }],
    hashtag: "#관심수집가"
  },
  {
    id: "excitement-booster",
    name: "흥분부스터",
    subtitle: "흥분하면 멈출 수 없어요",
    tags: ["#흥분주의", "#에너지폭발", "#브레이크없음"],
    emoji: "🎆",
    color: "from-sky-400 to-blue-400",
    mbti: "ISFP",
    summary: "흥분하면 제어 불가능한 에너지 폭탄",
    description: "신나면 멈출 수가 없어요! 점프하고 뛰고 짖고... 흥분의 끝을 모르는 열정 가득 타입. 진정될 때까지 좀 걸리지만 그만큼 표현이 솔직해요.",
    behaviors: ["반갑다고 미친듯이 점프", "흥분하면 짖음 폭발", "진정되는 데 시간 걸림", "감정 표현 200%"],
    aloneReaction: "흥분했다가 진정 후 기다림",
    recommendedRoutine: ["흥분 조절 훈련", "진정 시키는 루틴", "차분한 인사 연습"],
    playStyle: ["에너지 발산 놀이", "진정 후 보상", "흥분 조절 게임"],
    strengths: ["솔직한 감정표현", "열정 가득", "기쁨 200%"],
    careAdvice: ["흥분 조절 훈련 필수", "차분한 인사 연습", "너무 흥분시키지 않기"],
    compatibility: [{ type: "차분한 보호자", score: 95 }, { type: "인내심 있는 보호자", score: 92 }],
    hashtag: "#흥분부스터"
  },
  {
    id: "home-explorer",
    name: "집안탐사대",
    subtitle: "집 구석구석이 탐험지예요",
    tags: ["#실내탐험가", "#구석구석", "#호기심"],
    emoji: "🔦",
    color: "from-indigo-500 to-violet-500",
    mbti: "INTP",
    summary: "집안 구석구석을 탐험하는 실내 모험가",
    description: "밖보다 집이 더 재밌어요! 소파 밑, 침대 아래, 옷장 안... 집 구석구석 탐험하느라 바빠요. 숨겨진 공간 찾는 게 취미!",
    behaviors: ["소파 밑 탐험", "좁은 공간 들어가기", "새로운 구석 발견하면 흥분", "집안 지리 완벽 파악"],
    aloneReaction: "집 탐험하다 보호자 맞이",
    recommendedRoutine: ["안전한 탐험 공간 확보", "숨기기 놀이", "실내 보물찾기"],
    playStyle: ["숨바꼭질", "보물찾기", "퍼즐 피더"],
    strengths: ["호기심 대왕", "독립심", "재밌어함"],
    careAdvice: ["위험한 공간 막기", "탐험 욕구 충족", "숨기기 놀이 해주기"],
    compatibility: [{ type: "넓은 집", score: 96 }, { type: "안전한 환경", score: 93 }],
    hashtag: "#집안탐사대"
  },
  {
    id: "energy-firework",
    name: "에너지폭죽",
    subtitle: "터지면 끝날 때까지 안 멈춰요",
    tags: ["#폭죽", "#무한에너지", "#브레이크없음"],
    emoji: "🎇",
    color: "from-cyan-500 to-teal-500",
    mbti: "INTJ",
    summary: "한번 터지면 멈출 수 없는 에너지 덩어리",
    description: "놀이 시작하면 끝날 때까지 안 멈춰요! 폭죽처럼 터지는 에너지! 지칠 때까지 놀다가 갑자기 기절하듯 잠드는 ON/OFF 타입.",
    behaviors: ["놀이 시작하면 폭발", "지칠 때까지 안 멈춤", "갑자기 기절 잠", "ON/OFF 확실함"],
    aloneReaction: "에너지 소모 후 깊은 잠",
    recommendedRoutine: ["충분한 놀이 시간", "에너지 발산 후 휴식", "ON/OFF 리듬 맞추기"],
    playStyle: ["격렬한 놀이", "달리기", "터그놀이 무한반복"],
    strengths: ["체력 최강", "ON/OFF 확실", "놀이 즐기는 능력"],
    careAdvice: ["충분한 에너지 발산", "ON/OFF 리듬 존중", "갑자기 잠들어도 깨우지 않기"],
    compatibility: [{ type: "활동적인 보호자", score: 94 }, { type: "에너지 감당 가능", score: 91 }],
    hashtag: "#에너지폭죽"
  },
  {
    id: "love-express",
    name: "사랑직진러",
    subtitle: "사랑은 직진이다!",
    tags: ["#직진러", "#애정표현왕", "#직구애정"],
    emoji: "💕",
    color: "from-rose-400 to-pink-400",
    mbti: "ESFP",
    summary: "사랑을 숨기지 않는 솔직한 애정왕",
    description: "좋으면 좋다고 표현해요! 꼬리 흔들고, 핥고, 뛰어오르고... 애정 표현에 거침이 없어요. 사랑은 직진! 돌려말하는 거 없어요!",
    behaviors: ["보면 바로 뛰어듦", "핥핥 세례", "꼬리 1000rpm", "애정 표현 200%"],
    aloneReaction: "보고 싶어서 울먹거림",
    recommendedRoutine: ["충분한 스킨십 시간", "애정 표현 받아주기", "함께하는 시간 확보"],
    playStyle: ["스킨십 놀이", "안고 놀기", "함께 낮잠"],
    strengths: ["솔직한 애정", "유대감 최고", "밝은 성격"],
    careAdvice: ["애정 표현 받아주기", "충분한 스킨십", "사랑 돌려주기"],
    compatibility: [{ type: "스킨십 좋아하는 보호자", score: 99 }, { type: "애정 표현 풍부한 사람", score: 97 }],
    hashtag: "#사랑직진러"
  },
  {
    id: "guard-captain",
    name: "경계대장",
    subtitle: "내가 이 집을 지킨다!",
    tags: ["#경비견", "#경계심", "#집지킴이"],
    emoji: "🛡️",
    color: "from-amber-500 to-yellow-500",
    mbti: "ISTP",
    summary: "집과 가족을 지키는 경비대장",
    description: "낯선 사람? 경계! 이상한 소리? 경고 짖음! 우리 집과 가족을 지키는 게 내 사명이에요. 경계심이 강하지만 그만큼 충성심도 강해요!",
    behaviors: ["낯선 사람에게 경계 짖음", "문 소리에 바로 반응", "가족 지키려는 자세", "집 주변 순찰"],
    aloneReaction: "집 경비하며 기다림",
    recommendedRoutine: ["적절한 경계 칭찬", "과도한 짖음 조절 훈련", "사회화 교육"],
    playStyle: ["순찰 놀이", "경비견 훈련", "터그놀이"],
    strengths: ["충성심 최고", "경계심", "용감함"],
    careAdvice: ["과도한 경계 조절", "사회화 교육 필수", "적절한 칭찬"],
    compatibility: [{ type: "보호 본능 원하는 보호자", score: 96 }, { type: "짖음 OK인 환경", score: 93 }],
    hashtag: "#경계대장"
  },
  {
    id: "adventure-instinct",
    name: "모험본능러",
    subtitle: "모험이 DNA에 있어요",
    tags: ["#모험가", "#탐험본능", "#야생본능"],
    emoji: "🏔️",
    color: "from-lime-400 to-green-400",
    mbti: "ESTJ",
    summary: "타고난 모험가 DNA를 가진 탐험왕",
    description: "새로운 곳? 무조건 가야지! 모험과 탐험이 DNA에 새겨진 진정한 탐험가. 두려움 없이 어디든 척척, 어떤 환경에도 적응하는 야생 본능!",
    behaviors: ["새로운 곳 = 흥분 200%", "두려움 없이 탐험", "어디든 적응", "야생 본능 살아있음"],
    aloneReaction: "다음 모험 기대하며 기다림",
    recommendedRoutine: ["새로운 산책 코스", "주말 탐험 여행", "다양한 환경 경험"],
    playStyle: ["야외 탐험", "새로운 장소 방문", "캠핑/등산"],
    strengths: ["모험심", "적응력", "용감함"],
    careAdvice: ["안전한 탐험 환경", "새로운 경험 제공", "야외 활동 기회"],
    compatibility: [{ type: "아웃도어 러버", score: 97 }, { type: "여행 자주 가는 보호자", score: 95 }],
    hashtag: "#모험본능러"
  }
]

// Helper function to get personality by id
export const getPersonalityById = (id: string) => personalityTypes.find(p => p.id === id)

// Helper function to get personality by name
export const getPersonalityByName = (name: string) => personalityTypes.find(p => p.name === name)

// Products mapped to personality types
export const personalityProducts: Record<string, { name: string; price: string; originalPrice?: string; tag: string; emoji: string; rating: number; reviews: number; bestseller?: boolean; reason: string }[]> = {
  "찐애착 베이비": [
    { name: "심장박동 인형", price: "45,000원", originalPrice: "55,000원", tag: "분리불안 완화", emoji: "🧸", rating: 4.9, reviews: 1247, bestseller: true, reason: "보호자 대신 안정감을 주는 필수템" },
    { name: "진정 디퓨저 리필", price: "28,000원", tag: "안정감", emoji: "💨", rating: 4.8, reviews: 892, reason: "페로몬 성분으로 불안 감소" },
    { name: "분리불안 훈련 키트", price: "35,000원", tag: "훈련용", emoji: "📦", rating: 4.7, reviews: 456, reason: "단계별 분리 연습 가이드" },
    { name: "보호자 냄새 담요", price: "32,000원", tag: "안정감", emoji: "🧣", rating: 4.8, reviews: 678, reason: "보호자 향기로 안심" },
  ],
  "호기심 대마왕": [
    { name: "3단계 퍼즐 피더", price: "32,000원", originalPrice: "42,000원", tag: "두뇌 자극", emoji: "🧩", rating: 4.9, reviews: 2341, bestseller: true, reason: "호기심 해소 + 두뇌 훈련 일석이조" },
    { name: "스너플 매트 XL", price: "38,000원", tag: "노즈워크", emoji: "🧶", rating: 4.8, reviews: 1567, reason: "냄새 탐험 본능 충족" },
    { name: "숨기기 좋은 간식 볼", price: "22,000원", tag: "탐험 놀이", emoji: "⚽", rating: 4.7, reviews: 934, reason: "찾는 재미가 있는 간식통" },
    { name: "인터랙티브 노즈워크", price: "45,000원", tag: "탐색 활동", emoji: "🔍", rating: 4.9, reviews: 789, reason: "레벨업 가능한 탐험 놀이" },
  ],
  "에너자이저 러버": [
    { name: "터그 로프 세트", price: "18,000원", originalPrice: "25,000원", tag: "함께 놀이", emoji: "🪢", rating: 4.9, reviews: 3421, bestseller: true, reason: "보호자와 함께 에너지 발산" },
    { name: "공던지기 런처", price: "35,000원", tag: "활동량 UP", emoji: "🎾", rating: 4.8, reviews: 1892, reason: "더 멀리, 더 오래 놀기" },
    { name: "프리스비 소프트", price: "15,000원", tag: "야외 놀이", emoji: "🥏", rating: 4.7, reviews: 2134, reason: "함께하는 야외 활동 필수템" },
    { name: "간식 파우치 (방수)", price: "25,000원", tag: "훈련용", emoji: "👜", rating: 4.8, reviews: 987, reason: "산책 중 훈련 보상용" },
  ],
  "폭주기관차 비글미": [
    { name: "에너지 소모 킥볼", price: "28,000원", originalPrice: "35,000원", tag: "체력 소모", emoji: "⚽", rating: 4.9, reviews: 2567, bestseller: true, reason: "지칠 줄 모르는 아이를 위한 필수품" },
    { name: "자동 공던지기 머신", price: "89,000원", tag: "무한 놀이", emoji: "🤖", rating: 4.7, reviews: 1234, reason: "보호자 체력 보존 + 아이 만족" },
    { name: "터프 씹기 장난감", price: "22,000원", tag: "스트레스 해소", emoji: "🦴", rating: 4.8, reviews: 1876, reason: "튼튼해서 쉽게 안 망가짐" },
    { name: "어질리티 훈련 세트", price: "75,000원", tag: "에너지 발산", emoji: "🏃", rating: 4.6, reviews: 567, reason: "집에서도 미니 운동장" },
  ],
  "핵인싸 파티피플": [
    { name: "강아지 명함 태그", price: "15,000원", tag: "소셜", emoji: "🏷️", rating: 4.8, reviews: 1432, bestseller: true, reason: "산책 중 친구 만들기 필수" },
    { name: "다견용 터그 장난감", price: "25,000원", originalPrice: "32,000원", tag: "함께 놀이", emoji: "🪢", rating: 4.7, reviews: 876, reason: "여러 친구와 동시에 놀기" },
    { name: "파티용 간식 대용량", price: "28,000원", tag: "사회화", emoji: "🍖", rating: 4.9, reviews: 2341, reason: "친구들과 나눠먹기 좋아요" },
    { name: "강아지 운동장 티켓 5회", price: "45,000원", tag: "사교활동", emoji: "🎫", rating: 4.8, reviews: 654, reason: "인싸들의 놀이터" },
  ],
  "똑똒이 뇌섹견": [
    { name: "고난도 퍼즐 토이", price: "42,000원", originalPrice: "55,000원", tag: "두뇌 풀가동", emoji: "🧠", rating: 4.9, reviews: 1876, bestseller: true, reason: "천재견을 위한 레벨업 퍼즐" },
    { name: "트릭 훈련 교재 + 간식", price: "35,000원", tag: "학습", emoji: "📚", rating: 4.8, reviews: 1234, reason: "새로운 재주 배우기" },
    { name: "음성 인식 장난감", price: "55,000원", tag: "스마트 토이", emoji: "🎙️", rating: 4.7, reviews: 567, reason: "명령어 학습 + 보상" },
    { name: "노즈워크 고급형", price: "48,000원", tag: "두뇌 자극", emoji: "🔍", rating: 4.8, reviews: 892, reason: "냄새로 문제 해결하기" },
  ],
  "유리멘탈 감성러": [
    { name: "진정 음악 스피커", price: "55,000원", originalPrice: "68,000원", tag: "안정감", emoji: "🎵", rating: 4.9, reviews: 1567, bestseller: true, reason: "천둥/불꽃 무서워하는 아이 필수" },
    { name: "케이지 커버 (차음)", price: "45,000원", tag: "안전공간", emoji: "🏠", rating: 4.8, reviews: 987, reason: "외부 자극 차단" },
    { name: "진정 간식 (카모마일)", price: "18,000원", tag: "안정", emoji: "🍪", rating: 4.7, reviews: 2134, reason: "천연 성분으로 마음 안정" },
    { name: "압박 조끼 (천둥셔츠)", price: "42,000원", tag: "불안 완화", emoji: "🦺", rating: 4.8, reviews: 876, reason: "포근한 압박감으로 안심" },
  ],
  "마이웨이 독립견": [
    { name: "자동 급식기", price: "89,000원", originalPrice: "110,000원", tag: "자동화", emoji: "🤖", rating: 4.8, reviews: 2341, bestseller: true, reason: "정해진 시간에 알아서 밥" },
    { name: "혼자 노는 장난감 세트", price: "35,000원", tag: "혼자놀이", emoji: "🎲", rating: 4.7, reviews: 1567, reason: "보호자 없어도 재밌어요" },
    { name: "개인 공간 베드", price: "65,000원", tag: "마이룸", emoji: "🛏️", rating: 4.9, reviews: 987, reason: "나만의 안전한 공간" },
    { name: "장시간 씹는 간식", price: "22,000원", tag: "혼자 시간", emoji: "🦴", rating: 4.8, reviews: 2876, reason: "오래오래 혼자 즐기기" },
  ],
  "쿨내진 관종이": [
    { name: "조용한 노즈워크 매트", price: "35,000원", originalPrice: "42,000원", tag: "조용한 놀이", emoji: "🧶", rating: 4.8, reviews: 1234, bestseller: true, reason: "시끄럽지 않게 두뇌 활동" },
    { name: "창가 쿠션", price: "45,000원", tag: "관찰 스팟", emoji: "🪟", rating: 4.7, reviews: 876, reason: "바깥 구경 최적 스팟" },
    { name: "저소음 장난감", price: "18,000원", tag: "조용한 놀이", emoji: "🧸", rating: 4.6, reviews: 567, reason: "삑삑 소리 없는 장난감" },
    { name: "안정감 베드 M", price: "55,000원", tag: "휴식", emoji: "🛏️", rating: 4.9, reviews: 1432, reason: "편안한 관찰 & 휴식" },
  ],
  "평화주의 도사견": [
    { name: "힐링 아로마 디퓨저", price: "38,000원", originalPrice: "48,000원", tag: "평화로움", emoji: "🌸", rating: 4.9, reviews: 1876, bestseller: true, reason: "평화로운 분위기 연출" },
    { name: "소프트 쿠션 베드", price: "58,000원", tag: "편안함", emoji: "☁️", rating: 4.8, reviews: 1234, reason: "구름같이 폭신한 잠자리" },
    { name: "릴렉싱 음악 USB", price: "15,000원", tag: "힐링", emoji: "🎶", rating: 4.7, reviews: 654, reason: "클래식 & 자연 소리 모음" },
    { name: "마사지 브러시", price: "22,000원", tag: "케어", emoji: "✨", rating: 4.8, reviews: 2341, reason: "빗질하면서 마사지까지" },
  ],
  "완벽균형 올라운더": [
    { name: "올인원 케어 박스", price: "55,000원", originalPrice: "72,000원", tag: "종합 케어", emoji: "📦", rating: 4.9, reviews: 2567, bestseller: true, reason: "뭐든 잘 맞는 만능 세트" },
    { name: "기본 훈련 키트", price: "32,000원", tag: "훈련", emoji: "🎓", rating: 4.8, reviews: 1432, reason: "기초부터 탄탄하게" },
    { name: "다용도 장난감 세트", price: "28,000원", tag: "놀이", emoji: "🎁", rating: 4.7, reviews: 987, reason: "상황별 다양한 놀이" },
    { name: "건강 간식 믹스", price: "22,000원", tag: "간식", emoji: "🍖", rating: 4.8, reviews: 3421, reason: "영양 균형 잡힌 간식" },
  ],
  "야생의 탐험가": [
    { name: "등산용 하네스", price: "45,000원", originalPrice: "58,000원", tag: "아웃도어", emoji: "🏔️", rating: 4.9, reviews: 1876, bestseller: true, reason: "어디든 함께 모험" },
    { name: "휴대용 물병 + 그릇", price: "25,000원", tag: "야외활동", emoji: "💧", rating: 4.8, reviews: 2341, reason: "산책 & 등산 필수템" },
    { name: "야광 LED 목줄", price: "22,000원", tag: "안전", emoji: "💡", rating: 4.7, reviews: 1234, reason: "밤 산책도 안전하게" },
    { name: "접이식 이동장", price: "68,000원", tag: "여행", emoji: "🧳", rating: 4.8, reviews: 876, reason: "어디든 함께 여행" },
  ],
  "순둥이 천사견": [
    { name: "소프트 터그 장난감", price: "18,000원", originalPrice: "25,000원", tag: "부드러운 놀이", emoji: "🧸", rating: 4.9, reviews: 1567, bestseller: true, reason: "순한 아이를 위한 부드러운 터그" },
    { name: "칭찬 간식 세트", price: "22,000원", tag: "긍정 강화", emoji: "🌟", rating: 4.8, reviews: 2134, reason: "착한 행동에 칭찬 보상" },
    { name: "안심 쿠션 베드", price: "48,000원", tag: "안정감", emoji: "💤", rating: 4.7, reviews: 987, reason: "순둥이의 안전한 휴식처" },
    { name: "자신감 훈련 가이드", price: "28,000원", tag: "훈련", emoji: "📖", rating: 4.6, reviews: 567, reason: "조금씩 자신감 키우기" },
  ],
  "원픽 집착러": [
    { name: "좋아하는 장난감 5세트", price: "35,000원", originalPrice: "45,000원", tag: "원픽 교체용", emoji: "🎯", rating: 4.8, reviews: 1234, bestseller: true, reason: "같은 종류 여러 개로 교체" },
    { name: "집중 훈련 키트", price: "42,000원", tag: "훈련", emoji: "🎓", rating: 4.9, reviews: 876, reason: "집중력 활용 고급 훈련" },
    { name: "한 가지 맛 간식 대용량", price: "28,000원", tag: "원픽 간식", emoji: "🦴", rating: 4.7, reviews: 1567, reason: "좋아하는 맛만 잔뜩" },
    { name: "내구성 좋은 장난감", price: "32,000원", tag: "오래가는", emoji: "💪", rating: 4.8, reviews: 2341, reason: "집착해도 안 망가짐" },
  ],
  "공감천재 힐링독": [
    { name: "함께 쓰는 담요", price: "38,000원", originalPrice: "48,000원", tag: "유대감", emoji: "🧣", rating: 4.9, reviews: 1876, bestseller: true, reason: "보호자와 함께 덮기" },
    { name: "스킨십 마사지 오일", price: "25,000원", tag: "케어", emoji: "💕", rating: 4.8, reviews: 1234, reason: "마사지하며 교감 시간" },
    { name: "포토 프레임 담요", price: "45,000원", tag: "추억", emoji: "📸", rating: 4.7, reviews: 654, reason: "우리의 추억을 담아" },
    { name: "힐링 간식 세트", price: "22,000원", tag: "함께 간식", emoji: "🍪", rating: 4.8, reviews: 2567, reason: "같이 먹는 힐링 타임" },
  ],
  "만능 적응 카멜레온": [
    { name: "여행용 풀세트", price: "75,000원", originalPrice: "95,000원", tag: "여행 필수", emoji: "✈️", rating: 4.9, reviews: 1567, bestseller: true, reason: "어디든 함께 떠나요" },
    { name: "접이식 밥그릇 세트", price: "18,000원", tag: "휴대용", emoji: "🥣", rating: 4.8, reviews: 2341, reason: "어디서든 밥 먹기" },
    { name: "다용도 캐리어", price: "68,000원", tag: "이동", emoji: "🧳", rating: 4.7, reviews: 987, reason: "비행기/자동차 모두 OK" },
    { name: "환경 적응 간식", price: "22,000원", tag: "스트레스 완화", emoji: "🌱", rating: 4.8, reviews: 876, reason: "새 환경 적응 도우미" },
  ],
}
